### ISSUE TITLE
Fix error Cannot find module '/var/task/node_modules/react'

### ISSUE THREAD

**Issue by fwang** [serverless-stack/open-next#125]
### From Kylem on Discord
https://discord.com/channels/983865673656705025/1027265626085019769/1110882498176622634

The error I am getting when hitting the lambda is:

```json
{
   "errorType": "Error",
   "errorMessage": "ENOENT: no such file or directory, open '/var/task/apps/next/node_modules/next/package.json'",
   "code": "ENOENT",
   "errno": -2,
   "syscall": "open",
   "path": "/var/task/apps/next/node_modules/next/package.json",
   "stack": [
       "Error: ENOENT: no such file or directory, open '/var/task/apps/next/node_modules/next/package.json'",
       "    at Object.openSync (node:fs:601:3)",
       "    at Object.readFileSync (node:fs:469:35)",
       "    at xe (file:///var/task/apps/next/index.mjs:4:11322)",
       "    at ue (file:///var/task/apps/next/index.mjs:4:10572)",
       "    at file:///var/task/apps/next/index.mjs:4:9489",
       "    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"
   ]
}
```

I am using a monorepo, so the 'node_modules' folder is in the root, not in the apps/next folder.

**Comment by fwang** [comment]
Fixed in v1.3.5
