### ISSUE TITLE
aws-sdk 3.363.0 breaks open-next build

### ISSUE THREAD

**Issue by Tietew** [serverless-stack/open-next#150]
After upgrading aws-sdk to 3.363.0, `open-next build` fails with following errors:
```
$ yarn open-next build
Next.js v13.4.7
OpenNext v2.0.3
Monorepo detected at PROJECT_ROOT

┌─────────────────────────────────┐
│ OpenNext — Building Next.js app │
└─────────────────────────────────┘

$ next build
(completed successfully)

┌──────────────────────────────┐
│ OpenNext — Generating bundle │
└──────────────────────────────┘

Bundling static assets...
Bundling cache assets...
Bundling server function...
✘ [ERROR] Could not resolve "@aws-sdk/middleware-endpoint"

    ../../node_modules/@aws-sdk/client-sqs/node_modules/@aws-sdk/client-sts/dist-cjs/commands/AssumeRoleWithSAMLCommand.js:4:38:
      4 │ const middleware_endpoint_1 = require("@aws-sdk/middleware-endpoint");
        ╵                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@aws-sdk/middleware-endpoint" as external to exclude it from the bundle,
  which will remove this error. You can also surround this "require" call with a try/catch block to
  handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "@aws-sdk/middleware-endpoint"

    ../../node_modules/@aws-sdk/client-sqs/node_modules/@aws-sdk/client-sts/dist-cjs/commands/GetFederationTokenCommand.js:4:38:
      4 │ const middleware_endpoint_1 = require("@aws-sdk/middleware-endpoint");
        ╵                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@aws-sdk/middleware-endpoint" as external to exclude it from the bundle,
  which will remove this error. You can also surround this "require" call with a try/catch block to
  handle this failure at run-time instead of bundle-time.

(snip repeated errors)
✘ [ERROR] Could not resolve "@aws-sdk/middleware-endpoint"
✘ [ERROR] Could not resolve "@aws-sdk/util-retry"
✘ [ERROR] Could not resolve "@aws-sdk/util-stream"
✘ [ERROR] Could not resolve "@aws-sdk/util-base64"

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Build failed with 25 errors:
../../node_modules/@aws-sdk/client-sqs/node_modules/@aws-sdk/client-sso-oidc/dist-cjs/SSOOIDCClient.js:6:38: ERROR: Could not resolve "@aws-sdk/middleware-endpoint"
../../node_modules/@aws-sdk/client-sqs/node_modules/@aws-sdk/client-sso-oidc/dist-cjs/commands/CreateTokenCommand.js:4:38: ERROR: Could not resolve "@aws-sdk/middleware-endpoint"
../../node_modules/@aws-sdk/client-sqs/node_modules/@aws-sdk/client-sso-oidc/dist-cjs/commands/RegisterClientCommand.js:4:38: ERROR: Could not resolve "@aws-sdk/middleware-endpoint"
../../node_modules/@aws-sdk/client-sqs/node_modules/@aws-sdk/client-sso-oidc/dist-cjs/commands/StartDeviceAuthorizationCommand.js:4:38: ERROR: Could not resolve "@aws-sdk/middleware-endpoint"
../../node_modules/@aws-sdk/client-sqs/node_modules/@aws-sdk/client-sso-oidc/dist-cjs/runtimeConfig.js:12:29: ERROR: Could not resolve "@aws-sdk/util-retry"
...
    at failureErrorWithLog (PROJECT_ROOT/node_modules/open-next/node_modules/esbuild/lib/main.js:1575:15)
    at PROJECT_ROOT/node_modules/open-next/node_modules/esbuild/lib/main.js:1033:28
    at PROJECT_ROOT/node_modules/open-next/node_modules/esbuild/lib/main.js:978:67
    at buildResponseToResult (PROJECT_ROOT/node_modules/open-next/node_modules/esbuild/lib/main.js:1031:7)
    at PROJECT_ROOT/node_modules/open-next/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (PROJECT_ROOT/node_modules/open-next/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (PROJECT_ROOT/node_modules/open-next/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (PROJECT_ROOT/node_modules/open-next/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [...snip...],
  warnings: []
}
```

At aws-sdk 3.363.0, some `@aws-sdk/middleware-*` and `@aws-sdk/util-*` packages have been moved to `@smithy/*`.
It seems the reason.

WORKAROUND: Locking aws-sdk 3.362.0 works correctly.

my package.json (excerpts):
``` json
{
  "dependencies": {
    "@aws-sdk/client-sesv2": "^3.363.0",
    "next": "^13.4.7",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "sharp": "^0.32.1",
    "swr": "^2.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.14",
    "open-next": "^2.0.3"
  }
}
```

**Comment by Tietew** [comment]
Sorry, `rm -rf node_modules && yarn install` resolves this issue.
My node_modules was broken.
