### ISSUE TITLE
Build failing if missing public directory

### ISSUE THREAD

**Issue by davidrhoderick** [serverless-stack/open-next#53]
I was deploying a lot with SST yesterday via the `NextjsSite` construct and it was working fine.  I started working on the project today and I was immediately getting the following error:

```
node:fs:1574
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, lstat '/home/davidrhoderick/Development/martingale/vrio-pages/preview/public'
    at lstatSync (node:fs:1574:3)
    at statFunc (node:internal/fs/cp/cp-sync:122:15)
    at getStatsSync (node:internal/fs/cp/cp-sync:123:19)
    at checkPathsSync (node:internal/fs/cp/cp-sync:72:33)
    at cpSyncFn (node:internal/fs/cp/cp-sync:58:42)
    at Object.cpSync (node:fs:2904:3)
    at createAssets (file:///home/davidrhoderick/.npm/_npx/a94ce00fc9d9ef90/node_modules/open-next/dist/build.js:248:8)
    at build (file:///home/davidrhoderick/.npm/_npx/a94ce00fc9d9ef90/node_modules/open-next/dist/build.js:26:5) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/home/davidrhoderick/Development/martingale/vrio-pages/preview/public'
}

Node.js v18.14.2
Error: There was a problem building the "Preview" StaticSite.

Trace: Error: There was a problem building the "Preview" StaticSite.
    at NextjsSite.runBuild (file:///home/davidrhoderick/Development/martingale/vrio-pages/node_modules/sst/constructs/SsrSite.js:252:19)
    at NextjsSite.buildApp (file:///home/davidrhoderick/Development/martingale/vrio-pages/node_modules/sst/constructs/SsrSite.js:215:18)
    at new SsrSite (file:///home/davidrhoderick/Development/martingale/vrio-pages/node_modules/sst/constructs/SsrSite.js:75:14)
    at new NextjsSite (file:///home/davidrhoderick/Development/martingale/vrio-pages/node_modules/sst/constructs/NextjsSite.js:28:9)
    at EmptyStack.PagesStack (/home/davidrhoderick/Development/martingale/vrio-pages/stacks/pages-stack.ts:57:19)
    at stack (file:///home/davidrhoderick/Development/martingale/vrio-pages/node_modules/sst/constructs/FunctionalStack.js:20:35)
    at App.stack (file:///home/davidrhoderick/Development/martingale/vrio-pages/node_modules/sst/constructs/App.js:489:16)
    at Object.stacks (/home/davidrhoderick/Development/martingale/vrio-pages/sst.config.ts:24:9)
    at Module.synth (file:///home/davidrhoderick/Development/martingale/vrio-pages/node_modules/sst/stacks/synth.js:54:20)
    at async file:///home/davidrhoderick/Development/martingale/vrio-pages/node_modules/sst/cli/commands/deploy.js:52:24
    at process.<anonymous> (file:///home/davidrhoderick/Development/martingale/vrio-pages/node_modules/sst/cli/sst.js:58:17)
    at process.emit (node:events:525:35)
    at process.emit (node:domain:489:12)
    at process._fatalException (node:internal/process/execution:149:25)
    at processPromiseRejections (node:internal/process/promises:288:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

Once I added the `public/` directory in my project, it passed.  However, this is not ideal because I don't need an empty `public/` directory and as I pass this project off to other team members, they would have to manually add an empty `public/` directory as version control will not sync this folder without contents by default (maybe there's a way to hack that but either way, there's an issue with the Open Next build if it _requires_ a folder that Next.js does not).

As I said, this is the `NextjsSite` construct, so it uses Open Next to build it via `npx`.  At the time of this error, the version of Open Next used was 0.7.0.

**Comment by martg0** [comment]
Hi @davidrhoderick! I am assuming you are using only the /api routes without any pages?
Which version of NextJS are you using?
If you don't have static files, or content, I would put the favicon.ico on the public directory in case you need a file on this directory.

**Comment by davidrhoderick** [comment]
That did the trick, thanks @martg0 !  Kinda funky that I need to have something in that folder though when it isn't necessary for `npm run dev` (and it could just be empty...).
